export const COMPANY_NAME = "Precipice Technology";
export const COMPANY_LEGAL_NAME = "Precipice Technology LLC";
export const PRODUCT_ATTRIBUTION = `Product of ${COMPANY_LEGAL_NAME}`;

export function copyrightLine(): string {
  return `© ${new Date().getFullYear()} ${COMPANY_LEGAL_NAME}.`;
}

export const REPORT_FOOTER = `Tenant Hawk · Read-only Microsoft 365 scan · ${PRODUCT_ATTRIBUTION}`;

export const REPORT_FOOTER_LINE = `Generated by Tenant Hawk · ${PRODUCT_ATTRIBUTION} · Read-only tenant scan`;
