import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { ExportFinding, ExportMeta } from "@/lib/export/csv";
import { grade } from "@/lib/scan/score";

export function buildFindingsPdf(
  meta: ExportMeta,
  findings: ExportFinding[],
): Uint8Array {
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "letter" });
  const margin = 48;
  let y = margin;

  doc.setFontSize(18);
  doc.setTextColor(37, 99, 235);
  doc.text("Tenant Hawk", margin, y);
  y += 22;

  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text("Tenant health report", margin, y);
  y += 20;

  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text(`Tenant: ${meta.tenant}`, margin, y);
  y += 14;
  doc.text(`Scanned: ${meta.scannedAt}`, margin, y);
  y += 14;
  doc.text(`Mode: ${meta.mode}`, margin, y);
  y += 14;

  const scoreLabel =
    meta.score != null ? `${meta.score} (${grade(meta.score)})` : "—";
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text(`Health score: ${scoreLabel}`, margin, y);
  y += 24;

  autoTable(doc, {
    startY: y,
    head: [["Severity", "Category", "Finding", "Impact"]],
    body: findings.map((f) => [
      f.severity,
      f.category,
      f.title,
      f.impactUsd != null ? `$${f.impactUsd.toLocaleString()}/mo` : "—",
    ]),
    styles: { fontSize: 8, cellPadding: 4 },
    headStyles: { fillColor: [37, 99, 235] },
    margin: { left: margin, right: margin },
  });

  const finalY = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable
    ?.finalY;
  let detailY = (finalY ?? y) + 28;

  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Remediation details", margin, detailY);
  detailY += 16;

  for (const f of findings.slice(0, 25)) {
    if (detailY > doc.internal.pageSize.getHeight() - 72) {
      doc.addPage();
      detailY = margin;
    }
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(`• ${f.title}`, margin, detailY);
    detailY += 12;
    doc.setTextColor(71, 85, 105);
    const lines = doc.splitTextToSize(f.remediation || f.description, 500);
    doc.text(lines, margin + 8, detailY);
    detailY += lines.length * 11 + 8;
  }

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    "Generated by Tenant Hawk · Read-only tenant scan · Not affiliated with Microsoft",
    margin,
    doc.internal.pageSize.getHeight() - 32,
  );

  return new Uint8Array(doc.output("arraybuffer"));
}
