/** True when remediation was generated by OpenAI (not template fallback). */
export function isAiRemediation(model: string): boolean {
  return model !== "fallback" && !model.endsWith("-fallback");
}
